{{- if and .Values.alertmanager.enabled .Values.alertmanager.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "monitoring-pack.alertmanager.fullname" . }}
  namespace: {{ include "monitoring-pack.namespace" . }}
  labels:
    {{- include "monitoring-pack.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.alertmanager.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.alertmanager.persistence.size }}
  {{- if .Values.alertmanager.persistence.storageClass }}
  storageClassName: {{ .Values.alertmanager.persistence.storageClass }}
  {{- end }}
{{- end }}
