{{- if and .Values.grafana.enabled (not .Values.grafana.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-pack.grafana.fullname" . }}
  namespace: {{ include "monitoring-pack.namespace" . }}
  labels:
    {{- include "monitoring-pack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
{{- end }}
